import Link from "next/link";
import { notFound } from "next/navigation";
import { CheckCircle2, Clock, Mail, Search, Users } from "lucide-react";
import { ReviewStatusBadge, StepStatusBadge } from "@/components/status-badge";
import { ScorePill } from "@/components/score-pill";
import { StatCard } from "@/components/stat-card";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getTaskBundle } from "@/server/storage/json-store";
import { formatDateTime } from "@/lib/utils";

export const dynamic = "force-dynamic";

interface Params {
  params: Promise<{
    taskId: string;
  }>;
}

export default async function TaskRunPage({ params }: Params) {
  const { taskId } = await params;
  const bundle = await getTaskBundle(taskId);

  if (!bundle) notFound();

  const { task, customers, drafts } = bundle;
  const averageScore = Math.round(
    customers.reduce((sum, customer) => sum + customer.buyerFitScore, 0) / customers.length
  );

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-normal">{task.normalizedProduct}</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Task {task.id} created {formatDateTime(task.createdAt)}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Button asChild variant="outline">
            <Link href={`/tasks/${task.id}/review`}>Human review</Link>
          </Button>
          <Button asChild>
            <Link href="/customers">Open CRM</Link>
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-4">
        <StatCard icon={Search} label="Keywords" value={task.keywords.length} />
        <StatCard icon={Users} label="Customers" value={customers.length} />
        <StatCard icon={Mail} label="Drafts" value={drafts.length} />
        <StatCard icon={CheckCircle2} label="Avg score" value={averageScore} />
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_340px]">
        <Card>
          <CardHeader>
            <CardTitle>Workflow run</CardTitle>
            <CardDescription>LangGraph.js execution timeline.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {task.steps.map((step, index) => (
                <div
                  className="grid gap-3 rounded-md border p-3 md:grid-cols-[32px_1fr_120px]"
                  key={step.key}
                >
                  <div className="flex h-7 w-7 items-center justify-center rounded-md bg-muted text-xs font-semibold">
                    {index + 1}
                  </div>
                  <div>
                    <div className="text-sm font-medium">{step.label}</div>
                    <div className="mt-1 text-sm text-muted-foreground">{step.summary}</div>
                  </div>
                  <div className="flex items-start justify-start md:justify-end">
                    <StepStatusBadge status={step.status} />
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Review gates</CardTitle>
              <CardDescription>Approvals are human-controlled in the MVP UI.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="flex items-center justify-between rounded-md border p-3">
                <span className="text-sm">Keywords</span>
                <ReviewStatusBadge status={task.keywordReviewStatus} />
              </div>
              <div className="flex items-center justify-between rounded-md border p-3">
                <span className="text-sm">Email drafts</span>
                <ReviewStatusBadge status={task.emailReviewStatus} />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Keywords</CardTitle>
              <CardDescription>Generated by the keyword agent.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex flex-wrap gap-2">
                {task.keywords.map((keyword) => (
                  <span className="rounded-md border bg-muted px-2 py-1 text-xs" key={keyword}>
                    {keyword}
                  </span>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Top customers</CardTitle>
          <CardDescription>CRM records generated from the workflow.</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Company</TableHead>
                <TableHead>Market</TableHead>
                <TableHead>Contact</TableHead>
                <TableHead>Score</TableHead>
                <TableHead>Draft</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {customers.slice(0, 10).map((customer) => (
                <TableRow key={customer.id}>
                  <TableCell>
                    <Link className="font-medium text-primary" href={`/customers/${customer.id}`}>
                      {customer.companyName}
                    </Link>
                    <div className="text-xs text-muted-foreground">{customer.domain}</div>
                  </TableCell>
                  <TableCell>{customer.country}</TableCell>
                  <TableCell>
                    <div>{customer.contactName}</div>
                    <div className="text-xs text-muted-foreground">{customer.contactTitle}</div>
                  </TableCell>
                  <TableCell>
                    <ScorePill score={customer.buyerFitScore} />
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-1 text-xs text-muted-foreground">
                      <Clock className="h-3.5 w-3.5" />
                      {drafts.find((draft) => draft.customerId === customer.id)?.status ?? "draft"}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
